#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_37
#define AUDIO_I2S_GPIO_WS GPIO_NUM_34
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_36
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_35
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_33

#define AUDIO_CODEC_PA_PIN GPIO_NUM_11
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_18
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_17
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO GPIO_NUM_6
#define BOOT_BUTTON_GPIO GPIO_NUM_5

#endif // _BOARD_CONFIG_H_
